Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,22 +4,24 @@ jobs:
   my-job:
      runs-on: ubuntu-latest
      steps:
-       - name: Checkout code
-         uses: actions/checkout@v2
-       - name: set nodejs
-         uses: actions/setup-node@v2
-         with:
-           node-version: '18'
+        - name: Checkout code
+          uses: actions/checkout@v2
+        - name: set nodejs
+          uses: actions/setup-node@v2
+          with:
+            node-version: '18'
 
-        - name: install package json
+        - name: Install dependencies
           run: npm install
-
-        - name: Run testing
-          run: |
-          output=$(node dist/Test1.js)
-
-          if[ $output -ne 0]; then
-            echo "Error: code $output"
-            exit 1
-          fi
         
+        - name: run test
+          run: |
+            output=$(node dist/Test1.js)
+
+            if [ "$output" -eq 0 ]; then
+              echo "Test passed"
+            else
+              echo "Test failed"
+              exit 1
+            fi
+
